### PR TITLE
rewrite packaging

### PR DESCRIPTION
**Pull request by Artox**
I would like to discuss a different approach to managing the kodi packaging scripts:

As there are many different configurations to build kodi for from hardware accelrators to window systems, I thought it might be a good idea to be able to generate packaging in a generic fashion.

So I developed this make.sh script, which can format files in preprocessor style (ifdef).
This allows to specify all possible build-dependencies on raspberrypi or i.mx6 packages, for framebuffer and for x11, even conflicting ones in just one control.in file.
The script is then told which window-system, GL implementation and target hardware to use, and generates a complete debian packaging folder that can be simply thrown on top of the raw kodi source tree, and built.

This is not yet a drop-in replacement for the existing packaging, as I only focused on one specific piece of target hardware, and removed many hardcoded dependencies which I hope dh-shlibdeps will pull in itself when needed.  Short story: I might have broken all systems, so this needs reviewing if you like it.

For now, I would like to hear what you think about this, and whether further work should be put.

Some plus-points why I think this is awesome:
- manage all kodi configurations in one set of packaging files
- simplify adding new configurations
- potentially extendable to e.g. autogenerated package names, such as kodi-fb-gles-imx6, or kodi-x11-gl-generic

### CODE REVIEW

**Comment by wsnipex** [comment]
I like the general idea to unify packaging for all archs.

That said, I think this could be done with much less changes. Most of it could be directly in rules.

As you said, everything but imx is broken by this in the current state and I'd guess not even imx works properly, since you removed the hardcoded dependencies.
Those are there for a reason: We dyload those libs.

finally, this also breaks all our packaging scripts.

**Comment by Artox** [comment]
Yes, even imx is broken currently. I intend to have a build ready soon enough to play around with on my test machines and see what shlibdeps really does.

Now what troubled me most was build-depends. You can't do that in rules.
Thats the main reason I was inventing this preprocessor-like formatting, because you can't just add Build-Depends: imx-gpu-viv-fb-dev. It will conflict with mesa and-or raspberrypi userspace and break many other builds where the package isnt even available in repos.

About doing decisions in rules file: I was presented with choices I did not want to /could not make. Like, do I build for X11 or Framebuffer, or SDL?
I am targeting X11 Debian Linux, but kodi-imx does not work with x11 so ......

The reason why I rmeoved all those hardcoded dependencies is simple: I wanted to check which of these shlibdeps will pull in on its own (I wasn't aware of dyloading, so one could just copy that back).
Not to forget that when dependency-lists are long, I get scared quickly.

**Comment by wsnipex** [comment]
you can easily predefine build depends for various platforms in var_info and then just string replace/read into a variable in rules. Same for configure switches.
Deleting all those symlinks and .unified files is ok for me, but not changing the overall workflow.
The result still has to work as before with debuild.

**Comment by Artox** [comment]
I see. I will have a new look at var_info and try something out. I will let you know soon™ how that goes.

**Comment by wsnipex** [comment]
it doesn't even have to be in var_info, you can define vars directly in rules as well.

**Pull request closed without merging**
