### PR TITLE
Packaging fix for PR#20506

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by basilgello** [comment]
@wsnipex this one is a follow-up for xbmc/xbmc#20506

**Comment by basilgello** [comment]
Do I also need to backport this commit to Matrix branch following xbmc/xbmc#20507 ?

**Comment by wsnipex** [comment]
yes, since you backported the PR without even waiting a single day for PPA and some addon builds

**Comment by basilgello** [comment]
> yes, since you backported the PR without even waiting a single day for PPA and some addon builds

Moment! :)

As for builds, I tested building all addons supported in Debian unstable / testing (48 addons) on March 21st for amd64 + i386 + armhf.
April 9th it was all uploaded to experimental and 11th to unstable. Two more days and Kodi will be in testing. No issues spotted so far!

**Comment by basilgello** [comment]
#41

**Pull request merged**
